// Code generated by hertz generator.

package main

import (
	"go_tiktok_project/common/dal/mysql"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(
		server.WithHostPorts("0.0.0.0:6770"),
	)

	mysql.InitDB()
	register(h)
	h.Spin()
}
